### PR TITLE
removing all the uneeded stuff from blobmoji

### PR DESCRIPTION
**Pull request by SirCipherz**
since we only need the images i removed all the python stuff and anything that were not in the right directory, i also edited the README file to add the source. finally i did a little chmod +x on gen.sh because i was tired of typing sh gen.sh instead of ./gen.sh

### CODE REVIEW

**Comment by miacate** [comment]
What if, I just make a fork of blobmoji, and remove all of it's python code, and use that as the submod?

**Comment by SirCipherz** [comment]
> What if, I just make a fork of blobmoji, and remove all of it's python code, and use that as the submod?

why would we need a submodule ?

**Comment by miacate** [comment]
I feel like it would be better to use a submodule then to upload a bunch of pngs in the git project

**Comment by SirCipherz** [comment]
> I feel like it would be better to use a submodule then to upload a bunch of pngs in the git project

it doesn't change anything, you still have a git repo with a lot of pngs in it, and you have a repo that is not used anywhere else

**Comment by miacate** [comment]
That is correct... but I think it'd be better if I uploaded a compiled copy of the emojis, this would likely fix #1

**Comment by miacate** [comment]
I'll compile a copy of blobmoji over the next few hours, then checkout the pr and add them in.

**Comment by SirCipherz** [comment]
> That is correct... but I think it'd be better if I uploaded a compiled copy of the emojis, this would likely fix #1

why would it fix #1 ?

**Comment by miacate** [comment]
_Likely_ I'll be able to match the missing emojis after they are all compiled. ie: all the flags can't be matched unless blobmoji is compiled

**Comment by miacate** [comment]
Blobmoji literally just uses the male emojis as the genderless ones.. Closing this cause I did it by hand using a submod

**Pull request closed without merging**
